apiVersion: v2
name: zookeeper
description: ZooKeeper wrapper Chart
type: application
version: 1.0.2
appVersion: "3.9"
dependencies:
  - name: zookeeper
    version: "13.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
