zookeeper:
  ## ZooKeeper 副本数
  replicaCount: 3

  ## 持久化存储
  persistence:
    enabled: true
    size: 4Gi

  ## 资源配置
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

  ## 服务配置
  service:
    type: ClusterIP
    ports:
      client: 2181
      follower: 2888
      election: 3888

  ## metrics 监控
  metrics:
    enabled: false
