apiVersion: v2
name: redis
description: Redis wrapper Chart
type: application
version: 1.0.0
appVersion: "7.2"
dependencies:
  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
