apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "filebrowser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filebrowser.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnv }}
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /home/filebrowser/data/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.persistence.srv.enabled }}
            - name: srv
              mountPath: /srv
            {{- else if .Values.persistence.srv.existingClaim }}
            - name: srv
              mountPath: /srv
            {{- end }}
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: /home/filebrowser/data
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "filebrowser.fullname" . }}-config
        {{- if .Values.persistence.srv.enabled }}
        - name: srv
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-srv
        {{- else if .Values.persistence.srv.existingClaim }}
        - name: srv
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.srv.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
