{{- if .Values.persistence.data.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-data
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
{{- end }}
{{- if and .Values.persistence.srv.enabled (not .Values.persistence.srv.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-srv
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.srv.accessMode }}
  {{- if .Values.persistence.srv.storageClassName }}
  storageClassName: {{ .Values.persistence.srv.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.srv.size }}
{{- end }}
