apiVersion: v2
name: grafana
description: Grafana wrapper Chart for data visualization and dashboards
type: application
version: 1.0.2
appVersion: "11.2"
dependencies:
  - name: grafana
    version: "8.x.x"
    repository: https://grafana.github.io/helm-charts
