apiVersion: v2
name: kafka
description: Kafka wrapper Chart
type: application
version: 1.0.1
appVersion: "3.8"
dependencies:
  - name: kafka
    version: "30.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
