apiVersion: v2
name: mysql
description: MySQL wrapper Chart
type: application
version: 1.0.2
appVersion: "8.0"
dependencies:
  - name: mysql
    version: "12.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
