apiVersion: v2
name: mongodb
description: MongoDB wrapper Chart
type: application
version: 1.0.2
appVersion: "7.0"
dependencies:
  - name: mongodb
    version: "15.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
