apiVersion: v2
name: logstash
description: Logstash wrapper Chart for log processing pipeline
type: application
version: 1.0.0
appVersion: "8.15"
dependencies:
  - name: logstash
    version: "8.5.x"
    repository: https://helm.elastic.co
